### ISSUE TITLE
Bug in autoconfigInterrupt()

### ISSUE THREAD

**Issue by fmafma** [Fattoresaimon/ArduinoDuPPaLib#10]
Hi!

The `autoconfigInterrupt()` method does not check for the `onIncrement` callback, and so does not set the according bit in the interrupt register.

This code should be added:

`
	if (onIncrement != NULL)
		reg |= RINC;
`

Thanks,

Frédéric

**Comment by Fattoresaimon** [comment]
Fixed!
Thank you!
