### ISSUE TITLE
I2C Encoder Mini - Long Push Duration

### ISSUE THREAD

**Issue by thegigi** [Fattoresaimon/ArduinoDuPPaLib#22]
I am using I2C Encoder Mini. Good product. I see that this can detect a long push. Is there any way to change the duration after which a long push event is being sent ?

thank you

**Comment by Fattoresaimon** [comment]
Hello,

Yes it's possible!
You have to write the double push period register.
Please check the datasheet at page 15.
Thank you!

**Comment by thegigi** [comment]
Thank you !
